version: "3"

services:
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - 3306:3306
      
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    ports:
      - 8080:80

volumes:
  database_data:
